language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
script: npm run build
after_script:
- "npm run test:cover"
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"
build:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: dist/umd/**/*
    skip_cleanup: true
  on:
    tags: true
