import './commands/google@latest/create';
import './commands/google@latest/marker';
import './commands/google@latest/popup';
import './commands/google@latest/point';
import './commands/google@latest/setCenter';
import './observers/google@latest/center';
import './observers/google@latest/click';
import './commands/common@latest/addData';
import './observers/common@latest/gps';
