import './commands/leaflet@latest/create';
import './commands/leaflet@latest/marker';
import './commands/leaflet@latest/popup';
import './commands/leaflet@latest/setCenter';
import './commands/leaflet@latest/point';
import './observers/leaflet@latest/center';
import './observers/leaflet@latest/click';
import './commands/common@latest/addData';
import './observers/common@latest/gps';
